### ISSUE TITLE
ValueError: Found array with 0 sample(s) (shape=(0, 23)) while a minimum of 1 isrequired by StandardScaler.

### ISSUE THREAD

**Issue by gemorningsun** [mondejar/ecg_classification_tf#8]
Runing train_SVM.py!
Loading MIT BIH arr (DS1) ...
Computing morphological features (DS1) ...
Wavelets ...
labels
writing pickle: /home/mjz/gzy/ecg-classification/python/ECG/mitbih_database/feat                                                                  ures/w_90_90_DS1_rm_bsline_maxRR_wvlt_MLII.p...
Loading MIT BIH arr (DS2) ...
Computing morphological features (DS2) ...
Wavelets ...
labels
writing pickle: /home/mjz/gzy/ecg-classification/python/ECG/mitbih_database/feat                                                                  ures/w_90_90_DS2_rm_bsline_maxRR_wvlt_MLII.p...
Traceback (most recent call last):
  File "run_train_SVM.py", line 54, in <module>
    main(multi_mode, 90, 90, do_preprocess, use_weight_class, maxRR, use_RR, nor                                                                  m_RR, compute_morph, oversamp_method, pca_k, feature_selection, do_cross_val, C_                                                                  value, gamma_value, reduced_DS, leads_flag)
  File "/home/mjz/gzy/ecg-classification/python/train_SVM.py", line 195, in main
    scaler.fit(tr_features)
  File "/home/mjz/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/da                                                                  ta.py", line 590, in fit
    return self.partial_fit(X, y)
  File "/home/mjz/anaconda3/lib/python3.5/site-packages/sklearn/preprocessing/da                                                                  ta.py", line 612, in partial_fit
    warn_on_dtype=True, estimator=self, dtype=FLOAT_DTYPES)
  File "/home/mjz/anaconda3/lib/python3.5/site-packages/sklearn/utils/validation                                                                  .py", line 431, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 23)) while a minimum of 1 is                                                                   required by StandardScaler.

**Comment by RayShark** [comment]
Well, I had the same error as you.
Have you got the solution yet? @gemorningsun

**Comment by banivyom** [comment]
shape=(0,23) shows that there is no data.
I'll suggest that check whether the read data part and write pickle file part of the code is working correctly or not, you might want to change the way it's been done.

**Comment by abhishekkathayat** [comment]
I faced the same problem.
In my case it was reading annotations file as binary in load_MITBIH.py at line 528. I replaced 'rb' with 'r' and it worked.

**Comment by NasimSulaiman** [comment]
I am having the same error , how to solve this !!!

**Comment by melika-kheirieh** [comment]
> 
> 
> I faced the same problem.
> In my case it was reading annotations file as binary in load_MITBIH.py at line 528. I replaced 'rb' with 'r' and it worked.

It worked for me. Thankful
