### ISSUE TITLE
How can I test single ecg record (in csv format)? 

### ISSUE THREAD

**Issue by karimkhanvi** [mondejar/ecg_classification_tf#9]
I have trained model, now I want to test it on my own ecg record which is in csv format. I checked all documentation and code files but I have no luck.

**Comment by mondejar** [comment]
Hi, in order to process your own data I suggest you to check and re-write the _load_signal_ method from the _load_MITBIH.py_ file. You may also need to segment your lead signals at beat level, and do some preprocessing
